### ISSUE TITLE
AMP Review #1 (submitted by Andrew)

### ISSUE THREAD

**Issue by melaniebeck** [fastforwardlabs/video-classification#1]
# Review Items

## `.project-metadata.yaml`
- [x] It'd be good to keep an Engines specification in addition to the runtimes spec. This way users who do not have runtimes for whatever reason aren't left guessing. Can we include an engine spec here after the runtime spec? (see any of the other released AMPs to copy/paste from)
- [x] The project is currently failing during the "Download Data" job. Looks like we're missing a package. I see that we are installing requirements in-line in the notebook, so this dependency is missing when the download is attempted. Might make sense to add a dedicated "Install Dependencies" step, or combine the install and download into one? Also, FYI this can be run as a Session task instead of a Job for simplification - see [this example](https://github.com/cloudera/CML_AMP_Tensorboard_on_CML/blob/master/.project-metadata.yaml) for reference
![image](https://user-images.githubusercontent.com/23462538/148272336-69b3b42b-00df-45ae-905a-d52803c63486.png)
- [ ] Side note: I notice that the runtime specified here is `edition: Standard`. Have you tried using a GPU runtime? Would it make sense to recommend that here? 
   - After writing this, I noticed the GPU callout in the README... out of curiosity, what issue was faced with GPUs?
- [x] I _believe_ the `kernel` parameter is incorrectly specified in the Job. My hunch is that this will fail if run on an Engine, but I haven't tested to be sure. See [this example](https://github.com/cloudera/CML_AMP_Structural_Time_Series/blob/master/.project-metadata.yaml) or the Cloudera AMP docs to confirm the correct syntax.

## `READMEmd`
- [x] Should we link to the first published blog post from the README as well as in the notebook?

## `video_classification.ipynb`
- [x] This link goes to a private Notion page instead of the public FFL blog:
![image](https://user-images.githubusercontent.com/23462538/148296023-9e70dc9a-04a1-4ff2-9fc3-5f1eec2f7f42.png)
- [x] Looks like this function is throwing an `IndexError` because the path to the data is one that is local to your dev environment. Changing the path to `/home/cdsw/data/raw/kinetics/400/val/*/` worked for me.
![image](https://user-images.githubusercontent.com/23462538/148297673-808bddbb-acc2-4279-bed1-00f823bd7880.png)
![image](https://user-images.githubusercontent.com/23462538/148297726-a933e685-fd51-4b43-8282-78ed36153c97.png)
- [x] With the data path corrected, it looks like the video's themselves still aren't displaying/playing in the notebook? I'm guessing this has something to do with IPython Display in notebook vs. lab... maybe?
![image](https://user-images.githubusercontent.com/23462538/148298803-f2475c78-41ae-48d3-a13d-cbda3c0e6728.png)
- [x] We can now fill in this placeholder link:
![image](https://user-images.githubusercontent.com/23462538/148299632-42e0a248-d0fd-4143-bb18-2ba5cf341cad.png)
- [x] During the evaluation section of the notebook, it appears that some of the files do not actually exist in the 400 that were downloaded initially? Could this error exist because previously we were referencing a local file path issue mentioned above (that may have had a larger subset of files)?
![image](https://user-images.githubusercontent.com/23462538/148301072-8504408e-db71-41e5-bfef-c163c0e54a81.png)

## Other Comments
- I LOVE the FancyArgumentParser 💥 
- Also LOVE the KineticsLoader class 💪 
- Also also LOVE the use of type hinting all over the place. I'm inspired. 🌟 
- Is it reasonable to demand a 16GB session to run this AMP? Maybe we could process 4 videos instead of 8 and cut the RAM requirement in half? Maybe Juno has an opinion on this?
- Super nitpicky...but I somehow noticed that the Cloudera source header in [setup.py](https://github.com/fastforwardlabs/video-classification/blob/b537ed19f346a1b126f480a65c1b2caa14a8d61a/setup.py#L4) has year == 2020, while all the others are 2021. I'm fine with keeping them all 2021, but all should be consistent probs.
- Can you share an image you'd like to use for the thumbnail in [the review doc](https://docs.google.com/document/d/1pOTnIycbCuqXO4_ViF518aNT3Phz07eyWWZuYSWLslU/edit)?
- Can you review/update the AMP tile metadata in the tracking doc (final repo name, short/long description, etc.)?

**Comment by melaniebeck** [comment]
@andrewrreed 

Thank you for such a thorough first pass! Again, apologies for the messy state of things. Turns out that a few small misses on my part resulted in big error messages. 

## Questions/Responses
> Also, FYI this can be run as a Session task instead of a Job for simplification

Dude. You're blowing my mind! I guess this should have been obvious, but we've always set up the .yaml installation using Jobs instead of Sessions. This is _way_ better. Thank you!

> I believe the kernel parameter is incorrectly specified in the Job. My hunch is that this will fail if run on an Engine, but I haven't tested to be sure

I've tested the AMP Setup Steps on Engines and Runtimes and they both completed successfully (likely thanks to your pointers on how to correctly specify engines). 

>With the data path corrected, it looks like the video's themselves still aren't displaying/playing in the notebook? 

TIL that in order for the HTML to properly display videos in the notebook, the pathnames need to be _relative_ to the notebook directory rather than _absolute_ paths. Don't know why that is but... TMYK. ⭐  Also, that whole mess should be fixed now. (I had a TODO to fix that hardcoded directory and somehow completely overlooked it. Oops.)

## Regarding resources

> Have you tried using a GPU runtime? Would it make sense to recommend that here? After writing this, I noticed the GPU callout in the README... out of curiosity, what issue was faced with GPUs?

I could not get the Session to recognize or utilize the GPU even after going through the documentation that Richa kindly provided. I assumed that it might be a physical problem with our GPUs (_again_) but I should revisit this and see if things have changed. I put this on the backburner because Daniel and I thought it would be better to have a fully-fledged AMP even if it only used CPUs, than to spend an inordinate amount of time debugging the GPU+TF issues. However, we're going to need the GPUs soon enough, so it's time to dig back into this. 

> Is it reasonable to demand a 16GB session to run this AMP? Maybe we could process 4 videos instead of 8 and cut the RAM requirement in half?

That's a reasonable compromise. On the one hand, I think it is important for users to understand the sheer amount of resources it takes to process videos but, on the other, we don't want it to be prohibitive. If we suspect that there are some users that simply won't have access to 16GiB then reducing the videos to 4 is a good solution. (Running the benchmarking script with only 8GiB would not be a good idea though. Then again, it's probably not a great idea to run that script without a GPU either. :P ) 

I'll do some additional testing to verify that 8GiB is sufficient for cutting down to 4 videos. 


## Other
> I LOVE the FancyArgumentParser 💥 

Ty! I lifted that from the Deep Learning for Question Answering AMP -- I spent so long developing that last year that I was thrilled to reuse the concept here!

> Can you share an image you'd like to use for the thumbnail in the review doc? Can you review/update the AMP tile metadata in the tracking doc (final repo name, short/long description, etc.)?

Hopefully, these last two points are all that's left to do and I will tackle those tomorrow.

**Comment by andrewrreed** [comment]
### Responses

> TIL that in order for the HTML to properly display videos in the notebook, the pathnames need to be relative to the notebook directory rather than absolute paths.

This is so so bizarre, but glad you found the fix!

> I could not get the Session to recognize or utilize the GPU even after going through the documentation that Richa kindly provided. I assumed that it might be a physical problem with our GPUs (again)...

I attempted to test out running the notebook on `eng-cml-cluster` and ran into the same issue where the GPU is not recognized out-of-the-box. Maybe this is a TF versioning / install setup thing? I'm ok with leaving this as is for now, but agree that we should revisit and get this working at some time in the future. 

> On the one hand, I think it is important for users to understand the sheer amount of resources it takes to process videos but, on the other, we don't want it to be prohibitive.

I agree on this. I'm ok with leaving at 16GB, but just wanted to pose this to @junosaur to get her thoughts?

### Wrap up

@melaniebeck  Everything runs as expected now, thanks for the quick turn around. I think we can call this review complete!

**Comment by junosaur** [comment]
@melaniebeck @andrewrreed 

> I'm ok with leaving at 16GB, but just wanted to pose this to @junosaur to get her thoughts?

I'm good with that too — I think there's an expectation that video is resource-heavy, and doing < 8 videos seems a little silly. I also did a quick sanity check on a cluster I know is resource-strapped (iEDH) and a 16GB session is still one of the default options.
